### PR TITLE
assets: add svg template

### PR DESCRIPTION
**Pull request by yoshuawuyts**
adds an svg template, makes it easy for others to get started with spec compliant stickers in tools such as sketch or illustrator. Cheers! :sparkles:

### CODE REVIEW

**Comment by erunion** [comment]
Finally!

**Comment by terinjokes** [comment]
Looks great. I'm not too familiar with SVG and tooling around it, but is it possible to add dimensions information on another layer (or group) and have it easily be hidden?

**Comment by yoshuawuyts** [comment]
@terinjokes I'm not sure how to do that. I've used the included svg image as the basis for several logos and both Sketch and Illustrator seem to have no problem with it; if someone knows how to change the dimensions that might perhaps be good as a follow up PR ?

**Comment by terinjokes** [comment]
Cool, I'll merge shortly.

**Pull request closed without merging**
