### PR TITLE
resolves #10

### LINKED ISSUE #10: Don't be a jerk
@maxogden suggests including a section that says don't be a jerk to people who didn't follow this spec, instead thank them for printing stickers.

### PR DESCRIPTION
**Pull request by iancrowther**
having re-visited the spec a few times now, I am in agreement with the issue - is a good shout

### CODE REVIEW

**Comment by jden** [comment]
:+1: lgtm

**Comment by terinjokes** [comment]
@iancrowther I like the wording, mind If I merge it in as part of index.bs instead?

**Comment by iancrowther** [comment]
no not at all - I was just trying to get the issue closed

**Comment by iancrowther** [comment]
what uses index.bs btw?

**Comment by terinjokes** [comment]
@iancrowther WHATWG's "BikeShed". It's how I generate the HTML for the gh-pages branch.

**Comment by iancrowther** [comment]
what needs to be done to close this?

**Pull request closed without merging**
